[package]
name = "spud-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
image = { workspace = true }
ratatui = { workspace = true }
spud-core = { path = "../spud-core" }
unicode-width = { workspace = true }
